<a href="https://colab.research.google.com/github/poline822-arch/datasets/blob/master/heathcare_stroke.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:


sns.set(style='whitegrid')

In [5]:
df=pd.read_csv('https://raw.githubusercontent.com/poline822-arch/healthcare-stroke-synthetic.csv/refs/heads/main/healthcare_stroke_synthetic.csv'
)
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,1,Male,50,0,0,Yes,Self-employed,Rural,239.10,45.00,smokes,0
1,2,Female,70,0,0,Yes,Private,Rural,210.30,25.60,formerly smoked,0
2,3,Female,95,0,1,Yes,Private,Urban,284.30,17.40,never smoked,1
3,4,Female,47,0,0,Yes,Private,Rural,280.50,30.80,Unknown,0
4,5,Male,18,0,0,Yes,Private,Urban,231.20,49.40,never smoked,0

number of rows and columns df.shape()
column name df.columns()
data types and non-null counts df.info()
summamary statistic for numeric columns df.describe()

In [7]:
#looking at the data

print('shape(rows, columns):', df.shape)
print(df.columns)

print('n\Data types and non-null counts:')
df.info()

print('\nSummary statistics (numeric columns):')
df.describe()

shape(rows, columns): (5000, 12)
Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')
n\Data types and non-null counts:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5000 non-null   int64
 1   gender             5000 non-null   object
 2   age                5000 non-null   int64
 3   hypertension       5000 non-null   int64
 4   heart_disease      5000 non-null   int64
 5   ever_married       5000 non-null   object
 6   work_type          5000 non-null   object
 7   Residence_type     5000 non-null   object
 8   avg_glucose_level  5000 non-null   float64
 9   bmi                5000 non-null   float64
 10  smoking_status     5000 non-null   object
 11  stroke             5000 non-null   int64
dtypes: float64(2), int64(5), object(5)
memory usage: 468.9+ KB

Summary statistics (numeric columns):

<>:6: SyntaxWarning: invalid escape sequence '\D'
<>:6: SyntaxWarning: invalid escape sequence '\D'
/tmp/ipykernel_2002/2206100649.py:6: SyntaxWarning: invalid escape sequence '\D'
  print('n\Data types and non-null counts:')

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00
mean,2500.50,49.95,0.10,0.05,173.50,31.14,0.28
std,1443.52,28.82,0.29,0.22,72.13,11.02,0.45
min,1.00,0.00,0.00,0.00,50.00,12.00,0.00
25%,1250.75,25.00,0.00,0.00,111.10,21.80,0.00
50%,2500.50,51.00,0.00,0.00,173.35,31.00,0.00
75%,3750.25,75.00,0.00,0.00,235.80,40.80,1.00
max,5000.00,99.00,1.00,1.00,300.00,50.00,1.00

before cleanning  #first 10 rows

In [8]:
df.head(10)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,1,Male,50,0,0,Yes,Self-employed,Rural,239.10,45.00,smokes,0
1,2,Female,70,0,0,Yes,Private,Rural,210.30,25.60,formerly smoked,0
2,3,Female,95,0,1,Yes,Private,Urban,284.30,17.40,never smoked,1
3,4,Female,47,0,0,Yes,Private,Rural,280.50,30.80,Unknown,0
4,5,Male,18,0,0,Yes,Private,Urban,231.20,49.40,never smoked,0
5,6,Male,5,0,0,Yes,Govt_job,Rural,242.60,19.70,never smoked,0
6,7,Male,83,0,0,No,children,Rural,206.20,29.20,never smoked,0
7,8,Female,26,0,0,No,Private,Rural,222.90,22.30,formerly smoked,0
8,9,Female,52,0,0,Yes,children,Urban,204.30,47.10,never smoked,1
9,10,Female,47,0,0,Yes,Private,Urban,127.90,32.90,smokes,0

#random sample of 5 row

In [16]:
df.sample(3, random_state=5)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
27,28,Female,25,0,0,Yes,Private,Rural,289.80,35.00,formerly smoked,0
1482,1483,Female,73,0,0,Yes,Govt_job,Rural,286.00,15.80,never smoked,1
3021,3022,Male,76,0,0,No,Private,Urban,192.00,16.60,smokes,0

summary statistic for all columns (numeric + non numeric)

In [10]:
df.describe(include='all')

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
count,5000.00,5000,5000.00,5000.00,5000.00,5000,5000,5000,5000.00,5000.00,5000,5000.00
unique,NaN,3,NaN,NaN,NaN,2,5,2,NaN,NaN,4,NaN
top,NaN,Female,NaN,NaN,NaN,Yes,Private,Rural,NaN,NaN,never smoked,NaN
freq,NaN,2498,NaN,NaN,NaN,3496,2916,2506,NaN,NaN,2474,NaN
mean,2500.50,NaN,49.95,0.10,0.05,NaN,NaN,NaN,173.50,31.14,NaN,0.28
std,1443.52,NaN,28.82,0.29,0.22,NaN,NaN,NaN,72.13,11.02,NaN,0.45
min,1.00,NaN,0.00,0.00,0.00,NaN,NaN,NaN,50.00,12.00,NaN,0.00
25%,1250.75,NaN,25.00,0.00,0.00,NaN,NaN,NaN,111.10,21.80,NaN,0.00
50%,2500.50,NaN,51.00,0.00,0.00,NaN,NaN,NaN,173.35,31.00,NaN,0.00
75%,3750.25,NaN,75.00,0.00,0.00,NaN,NaN,NaN,235.80,40.80,NaN,1.00
max,5000.00,NaN,99.00,1.00,1.00,NaN,NaN,NaN,300.00,50.00,NaN,1.00

clean column names(lowercases, replace spaces with undercores.
fix special missing values in bmi(e/g, "na'

In [19]:
df.columns = (df.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
    .str.replace('_ ', '_')
)
df.columns

Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

inspect unique values in bmi

In [22]:
df['bmi'].unique()[:20]

array([45. , 25.6, 17.4, 30.8, 49.4, 19.7, 29.2, 22.3, 47.1, 32.9, 34. ,
       12.3, 36.8, 23.6, 31.5, 32.2, 34.5, 43.3, 23.4, 21.7])

In [26]:
#check issing values again

df.isna().sum()

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [28]:
#descriptive analysis only numeric column data frame incluye allnumeric values

numeric_df=df.select_dtypes(include=['int64','float64'])
numeric_df.describe()

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00
mean,2500.50,49.95,0.10,0.05,173.50,31.14,0.28
std,1443.52,28.82,0.29,0.22,72.13,11.02,0.45
min,1.00,0.00,0.00,0.00,50.00,12.00,0.00
25%,1250.75,25.00,0.00,0.00,111.10,21.80,0.00
50%,2500.50,51.00,0.00,0.00,173.35,31.00,0.00
75%,3750.25,75.00,0.00,0.00,235.80,40.80,1.00
max,5000.00,99.00,1.00,1.00,300.00,50.00,1.00

In [29]:
#analyze the data sumarize

print('Age summary:')
print(df['age'].describe())

print('\nAverage Glucose level summar')
print(df['avg_glucose_level'].describe())

print('\nBMI summary:')
print(df['bmi'].describe())

Age summary:
count   5000.00
mean      49.95
std       28.82
min        0.00
25%       25.00
50%       51.00
75%       75.00
max       99.00
Name: age, dtype: float64

Average Glucose level summar
count   5000.00
mean     173.50
std       72.13
min       50.00
25%      111.10
50%      173.35
75%      235.80
max      300.00
Name: avg_glucose_level, dtype: float64

BMI summary:
count   5000.00
mean      31.14
std       11.02
min       12.00
25%       21.80
50%       31.00
75%       40.80
max       50.00
Name: bmi, dtype: float64

In [31]:
def show_category_distribution(col_name):
    counts=df[col_name].value_counts()
    percentages=df[col_name].value_counts(normalize=True)
    print(pd.DataFrame({'counts':counts, 'percentages':percentages.round(2)}))
    print(df[col_name].value_counts())

SyntaxError: invalid syntax (786410767.py, line 1)